# Generated by Django 6.1 on 2026-09-04 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('descricao', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ativo', models.BooleanField(default=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='kits/%Y/%m/')),
                ('produtos', models.ManyToManyField(related_name='kits', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Kit',
                'verbose_name_plural': 'Kits',
            },
        ),
    ]
