# Generated by Django 6.1 on 2026-09-04 17:58

import sistema_doceria.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kit',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[sistema_doceria.validators.validar_preco_positivo]),
        ),
    ]
