# Generated by Django 6.1 on 2026-09-04 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kits', '0001_initial'),
        ('produtos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Encomenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_entrega', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Em Producao', 'Em Produção'), ('Pronto', 'Pronto para Entrega/Retirada'), ('Concluida', 'Concluída'), ('Cancelada', 'Cancelada')], default='Pendente', max_length=30)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encomendas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Encomenda',
                'verbose_name_plural': 'Encomendas',
            },
        ),
        migrations.CreateModel(
            name='ItemEncomendaKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('encomenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encomendas.encomenda')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kits.kit')),
            ],
        ),
        migrations.AddField(
            model_name='encomenda',
            name='kits',
            field=models.ManyToManyField(blank=True, through='encomendas.ItemEncomendaKit', to='kits.kit'),
        ),
        migrations.CreateModel(
            name='ItemEncomendaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('encomenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encomendas.encomenda')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto')),
            ],
        ),
        migrations.AddField(
            model_name='encomenda',
            name='produtos',
            field=models.ManyToManyField(blank=True, through='encomendas.ItemEncomendaProduto', to='produtos.produto'),
        ),
    ]
