# Generated by Django 6.1 on 2026-09-04 17:58

import datetime
import sistema_doceria.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encomendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encomenda',
            name='data_entrega',
            field=models.DateField(default=datetime.date(2026, 9, 4), validators=[sistema_doceria.validators.validar_data_futura]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='encomenda',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[sistema_doceria.validators.validar_preco_positivo]),
        ),
    ]
